# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='alias',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='email',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='name',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='password',
        ),
        migrations.AddField(
            model_name='friends',
            name='friend_id',
            field=models.IntegerField(default=True),
            preserve_default=False,
        ),
    ]
